import { makeWorkflowTopic, type GuideTopic } from "./types";

export const analysisToolTopics: GuideTopic[] = [
  {
    ...makeWorkflowTopic({ slug: "formula-analysis", title: "公式结果分析与手机操作", summary: "先看实际开奖位置，再看公式表现，最后找到具体公式。", route: "/formula-result-statistics/analysis", keywords: ["分析", "手机", "放大", "200期", "返回", "保存视图"], purpose: "在同一页串起实际开奖、公式出现次数和原始计算记录。", when: "想看最近10至200期的落点趋势，或核对图里的某个数字时。", orientation: "顶部选择期数和排除/支持。下方四个区域分别是概览、落点趋势、公式诊断和明细核验。", steps: [{ title: "先选范围", body: "默认最近10期，可一直选到200期。手机上点筛选按钮，再选择类型、公式和对比条件。" }, { title: "看开奖落点", body: "次数表示当时有多少条公式得到实际开奖结果。位置按次数从多到少排，并列时采用相同名次。" }, { title: "点图核对", body: "点一期后进入明细，可以看到完整生肖、尾数等分类，0次不会省略。" }, { title: "放大查看", body: "电脑或手机都能点“放大图表”。宽图在图内左右滑，点关闭回到原来位置；电脑也可按Esc。" }, { title: "保留常用条件", body: "使用保存视图保留常用期数、动作、类型和公式。顶部返回箭头可以回到公式结果统计。" }], interpretation: "排除次数高只说明当时更多公式排除了它，不能理解为开奖概率更低。未开奖、缺少数据与0次不是一回事。", misunderstanding: "图表和公式健康都是历史分析，不是下一期开奖预测。横向滑动只发生在图表内部，页面其他操作保持正常。", troubleshooting: "内容正在加载时会显示提示；不要连续重复点击。数据期数不够时会说明实际可核对数量；点设置里的使用说明可查每张图怎么读。", related: ["landing-trend", "evidence-matrix", "formula-groups", "formula-effect"] }),
    screenshot: { src: "/help/screens/analysis-desktop.png", width: 1440, height: 1000, alt: "公式结果分析的电脑实际界面", caption: "电脑实图：范围、四个分析入口和主要结果集中排列。", callouts: [] },
    screenshots: [{ src: "/help/screens/analysis-mobile.png", width: 390, height: 844, alt: "公式结果分析的手机实际界面", caption: "手机实图：顶部保留返回和期数选择，简短指标两列排列，长图在下方完整保留。", callouts: [] }],
  },
  {
    ...makeWorkflowTopic({ slug: "formula-groups", title: "保存和比较公式组合", summary: "把常用公式存成一组，在同一批开奖中比较两边各对了几期。", route: "/candidate-pool", keywords: ["公式组合", "对比", "去重", "相同结果", "保存组合"], purpose: "看全部公式、自己挑的公式，或相同结果只算一份时，历史结果有什么差别。", when: "想整理常用公式，或了解重复意见是否影响排序时。", orientation: "在综合参考的“自选公式组合”中，上方勾选公式，下方保存名称和比较。", steps: [{ title: "挑选公式", body: "勾选想看的公式，也可以用“选择前10条”开始。没有选择时不会替你选其他公式。" }, { title: "保存组合", body: "写一个容易记住的名称，点“保存名称和当前选择”。以后在“我的公式组合”中直接选择；改名或调整勾选后再次保存即可。" }, { title: "选择范围", body: "默认最近10期，可选10至200期。选择比较全部与自选，或比较相同结果重复计算与只算一份。" }, { title: "开始比较", body: "点“开始比较”，等待两列成绩出现。条件变了要重新比较，旧成绩不会冒充新成绩。" }, { title: "核对具体期次", body: "展开“逐期查看两边结果”，看当时选了什么、实际开了什么；记录较多时可继续加载。" }], interpretation: "先看共同核对了多少期，再看每一列对、错几期。两边只使用都能核对的相同期次；前8个与前18个覆盖范围不同，不能把它们直接当成同样难度。", misunderstanding: "同样结果只算一份，只是一次单独比较，并不证明公式互相独立，也不会改动默认推荐、公式启停或原始被杀次数。历史多对几期不保证未来更好。", troubleshooting: "开始比较是灰色时，先选择至少一条可参与的公式。保存的公式被删除或停用后会提示并跳过；本机浏览器不能保存时，仍可使用当前勾选比较。", related: ["candidate-pool", "formula-health", "formula-observation"], screenshotSlug: "formula-groups" }),
    screenshot: { src: "/help/screens/formula-groups.png", width: 1148, height: 778, alt: "公式组合比较的实际界面", caption: "电脑实图：先保存选择，再用相同期数比较。数字来自截图时的历史记录。", callouts: [] },
    screenshots: [{ src: "/help/screens/formula-groups-mobile.png", width: 362, height: 1184, alt: "手机上的公式组合比较", caption: "手机实图：选项上下排列，两列成绩仍使用同一批期次。", callouts: [] }],
  },
  {
    ...makeWorkflowTopic({ slug: "formula-observation", title: "开始记录后的表现", summary: "先保存公式结果，等后续开奖再核对，避免把已知结果算成新成绩。", route: "/formula-detail", keywords: ["加入后", "观察", "记录", "版本", "新成绩"], purpose: "把本机提前保存过的公式结果，与后续开奖逐期核对。", when: "想观察一条公式接下来实际表现，而不只是看过去的成绩时。", orientation: "打开公式逐期明细，找到“开始记录后的表现”。这里与上方历史回顾分开，不会把以前已经开过的期次补进去。", steps: [{ title: "确认公式和最新开奖", body: "先核对公式名称及最新期号，确保使用的数据没有落后。" }, { title: "开始记录", body: "点“从现在开始记录这条公式”。系统保存此时算出的结果和时间，不把以前的期次补算为提前记录。" }, { title: "后续更新后查看", body: "打开本系统并更新数据时，会核对已保存结果，并为当前启用公式继续保存最新结果。没打开期间，不会假装每天都记录过。" }, { title: "查看每期结果", body: "展开列表，查看保存时间、当时结果和对应开奖。等待两期的公式会等所需期次到齐。" }], interpretation: "“已核对”只包括提前保存过、且后续开奖已齐的记录。对、错、待核对分开统计；停用后的旧结果仍会核对。", misunderstanding: "修改公式或计算设置后，新成绩与原版本分开保存。观察成绩不保证未来有效，且这些记录只保存在当前浏览器，不会自动同步到其他设备。", troubleshooting: "待核对较多时先检查缺失期次。读写失败会提示重试；每个版本最多保存2000期，每条公式最多20个版本，到达上限会暂停新增，已有记录不会被悄悄删除。", related: ["formula-detail", "formula-health", "data-health"], screenshotSlug: "formula-observation" }),
    screenshot: { src: "/help/screens/formula-observation.png", width: 1152, height: 186, alt: "公式观察记录的实际界面", caption: "先确认最新开奖再开始；开始后显示保存时间、已核对和待核对次数。日期缺失或记录过旧时不会新增观察。", callouts: [] },
  },
  {
    ...makeWorkflowTopic({ slug: "formula-effect", title: "公式表现的对照怎么看", summary: "不仅看对了多少，还要看这条公式本来覆盖了多大范围。", route: "/formula-detail", keywords: ["随机参考", "公式表现", "相差", "效果", "基准", "命中率"], purpose: "避免把“容易排对”误认为“公式一定更强”。", when: "比较不同公式，尤其是排除少量号码与选中多个生肖时。", orientation: "在公式逐期明细或公式诊断的展开内容中，看“这条公式表现怎么样”。先看已统计期数，再看实际比例和同条件参考。", steps: [{ title: "选期数", body: "默认最近10期，可改为10至200期。实际可核对数量以“已统计”为准。" }, { title: "读实际成绩", body: "例如排除正确9次、统计10期，就是90%。选中类公式则是实际结果落在公式选择范围内才算对。" }, { title: "读同条件参考", body: "假设49个号码机会相同：只排除1个号码，本来就有48个号码不在排除范围内，约98%。所以不能只因排对比例高就认定有效。" }, { title: "看具体错误", body: "展开出错期次并点一期，回到原始计算明细核对。" }], interpretation: "相差的是两个比例的百分点，不是提高了多少倍。不同生肖可能对应4个或5个号码，系统按实际号码数计算；需要连续多期都正确的公式也按对应规则比较。", misunderstanding: "这个参考是假设下的对照，不是未来预测。期数少、相邻验证重叠，或历史号码表不一致时，都不能据此证明有优势。", troubleshooting: "显示暂时不能比较时，仍可看历史实际对错；不要把缺少参考理解为0%。缺少或重复的数据不会凑进统计数量。", related: ["formula-detail", "formula-health", "historical-caveat"], screenshotSlug: "formula-effect" }),
    screenshot: { src: "/help/screens/formula-effect.png", width: 1152, height: 300, alt: "公式历史表现和同条件参考对照的实际界面", caption: "先读统计期数，再读实际比例与参考的差别；历史差别不等于未来优势。", callouts: [] },
  },
];
