import { makeWorkflowTopic } from "./types";

export const primaryModuleTopics = [
  makeWorkflowTopic({ slug: "dashboard", title: "首页", summary: "确认最新数据、公式数量和常用入口。", route: "/dashboard", keywords: ["概况", "最新开奖", "数据来源"], purpose: "首页只做运行概况和常用入口，不在这里重新计算一套结果。", when: "每天第一次打开系统时先看这里。", orientation: "先看顶部数据来源与最新期，再看流程卡和最新开奖。", steps: [{ title: "看数据", body: "确认最新期和数据来源。" }, { title: "看状态", body: "确认公式和依据数量不是异常的0。" }, { title: "进入任务", body: "按需要进入一键计算、统计或综合参考。" }], interpretation: "来源、期次、公式数量都合理，才能继续看后续分析。", misunderstanding: "首页数字是概况，不是开奖结果预测。", troubleshooting: "最新期不对时打开开奖数据并重新同步。", related: ["getting-started", "draws", "one-click"] }),
  makeWorkflowTopic({ slug: "one-click", title: "一键算公式", summary: "用指定一期一次计算全部启用公式。", route: "/one-click", keywords: ["计算", "公式输出", "最新一期"], purpose: "统一调用公式引擎，展示每条公式在当前期的真实输出和计算过程。", when: "同步新期开奖后，或修改公式、配置后重新计算时。", orientation: "先选最新或手动期次，再看每条公式的表达式、过程和输出。", steps: [{ title: "选择期次", body: "日常使用选最新一期；手动模式仅用于核对。" }, { title: "开始计算", body: "等待全部启用且可计算公式完成。" }, { title: "检查异常", body: "异常公式先进入逐期明细或校验。" }, { title: "阅读输出", body: "区分排除结果与支持结果。" }], interpretation: "输出集合表示该公式本期得到的结果，不等于下一期一定开或一定不开。", misunderstanding: "排除公式输出的是要排除的集合，不是推荐集合。", troubleshooting: "大量异常通常来自数据、属性配置或公式变量，按错误信息逐项核对。", related: ["formula-detail", "sample-check", "formula-result-statistics"] }),
  makeWorkflowTopic({ slug: "formula-result-statistics", title: "公式结果统计", summary: "统计各公式结果出现次数，并进入四区分析驾驶舱。", route: "/formula-result-statistics", keywords: ["formula result", "公式统计", "排除次数", "支持次数", "驾驶舱"], aliases: ["公式结果", "统计公式"], purpose: "把多条公式的输出按结果归并，显示每个生肖、尾数、半头、半波等被排除或支持了多少次。", when: "想知道同一期或最近十期公式意见集中在哪里时。", orientation: "先选最新/十期与排除/支持，再选结果类型；证据区展示贡献公式。", steps: [{ title: "选动作", body: "排除和支持必须分开看。" }, { title: "选类型", body: "选择生肖、尾数、半头、半波等；这里不统计单双大小。" }, { title: "点结果", body: "查看贡献该结果的原公式。" }, { title: "进入驾驶舱", body: "做10/30/50期、落点、健康和冲突分析。" }], interpretation: "次数是公式条数，每条公式对同一唯一结果每期只计1次。", misunderstanding: "次数高只说明公式意见集中，不代表实际开奖概率。", troubleshooting: "没有某类型时确认是否启用了对应公式；0次会在完整矩阵保留。", related: ["landing-trend", "evidence-matrix", "formula-health"] }),
  makeWorkflowTopic({ slug: "candidate-pool", title: "综合参考结果", summary: "汇总公式证据形成号码与生肖排序，并保留复盘档案。", route: "/candidate-pool", keywords: ["综合结果", "Top8", "候选池", "证据"], purpose: "把现有公式的支持与排除信号统一映射到号码和生肖，便于按证据查看排序。", when: "已确认开奖数据和公式计算正常后，用于最后汇总阅读。", orientation: "结果、证据、历史、组合和运行记录是不同工作区，先看结果再追证据。", steps: [{ title: "确认范围", body: "确认使用的数据期数和公式数量。" }, { title: "看排序", body: "选择Top8/12/18或生肖范围。" }, { title: "点候选", body: "查看支持与反对证据。" }, { title: "保存档案", body: "保存本次快照，等待后续开奖复盘。" }], interpretation: "分数来自现有公式证据的汇总；支持与反对必须一起看。", misunderstanding: "综合排序不是官方概率，也不是命中承诺。", troubleshooting: "结果为空时先看启用公式、公式可计算状态和同步数据。", related: ["one-click", "formula-result-statistics", "reports"] }),
  makeWorkflowTopic({ slug: "special-analysis", title: "专项概率观察", summary: "观察固定结构的历史分布、连续与遗漏。", route: "/special-analysis", keywords: ["概率观察", "遗漏", "连续", "固定模式"], purpose: "对选定专项按历史期次做描述性观察，帮助理解分布和遗漏。", when: "需要核对某个固定模式在历史数据中的位置与频次时。", orientation: "先读样本范围和口径，再看分布、连续和明细。", steps: [{ title: "选专项", body: "选择要观察的固定模式。" }, { title: "看样本", body: "确认期数足够且数据最新。" }, { title: "读分布", body: "同时看次数和样本总数。" }, { title: "核对明细", body: "点期次检查原始开奖。" }], interpretation: "次数、比例、连续和遗漏共同描述历史，单一最大值不够。", misunderstanding: "遗漏时间变长不代表下一期必然出现。", troubleshooting: "缺数据或样本太少时先同步，不要对不完整样本下结论。", related: ["draws", "historical-caveat", "troubleshooting"] }),
  makeWorkflowTopic({ slug: "draws", title: "开奖数据", summary: "同步、检查、人工补录和导出每期6+1号码。", route: "/draws", keywords: ["开奖", "同步", "6+1", "缺失期次"], purpose: "管理所有计算的基础数据；每期必须有6个平码和1个特码。", when: "最新期不对、页面为空、要补录或导出数据时。", orientation: "先看来源、最新期和总数，再使用同步、人工录入或导出。", steps: [{ title: "确认来源", body: "区分网站、云端、本地和人工记录。" }, { title: "同步", body: "从网站获取数据并先预览差异。" }, { title: "检查7码", body: "号码应为1-49且同一期不重复。" }, { title: "保存", body: "确认期号和号码后写入。" }], interpretation: "最新期、记录数、重复/冲突和更新时间共同决定数据是否健康。", misunderstanding: "同一期重复记录不一定相同；冲突记录必须人工核对。", troubleshooting: "同步失败可保留最后可用数据，但要留意更新时间并检查网络。", related: ["draw-structure", "data-health", "import"] }),
  makeWorkflowTopic({ slug: "rules", title: "公式管理", summary: "启用、停用、检查和维护全部公式。", route: "/rules", keywords: ["公式库", "启用", "停用", "健康"], purpose: "集中管理公式状态、来源、校验与冲突，不在这里伪造计算结果。", when: "新增公式后、计算异常时，或定期清理重复公式时。", orientation: "公式库、健康和对账是不同页签；先找状态，再做修改。", steps: [{ title: "筛选", body: "按类型、状态或名称找到公式。" }, { title: "看状态", body: "确认是否启用、可计算和已核对。" }, { title: "看明细", body: "进入逐期流水检查变量和错期。" }, { title: "谨慎修改", body: "修改前导出规则库备份。" }], interpretation: "启用表示参与计算；来源、样例和推荐标签不是参与门槛。", misunderstanding: "历史表现好不代表公式永远有效；样本和连续未通过同样重要。", troubleshooting: "异常先看具体错误，必要时停用并在公式编辑器修正。", related: ["formula-editor", "formula-detail", "formula-health"] }),
  makeWorkflowTopic({ slug: "sample-check", title: "公式校验", summary: "用手算样例核对原始值、归一化、映射和下一期结果。", route: "/sample-check", keywords: ["校验", "样例", "手算", "差异"], purpose: "验证程序计算是否与已知手算样例一致，并明确差异发生在哪一步。", when: "导入旧公式、修改解析、发现输出与人工计算不一致时。", orientation: "每条样例包含计算期、预期结果和程序结果；红色差异必须解释。", steps: [{ title: "选公式和期次", body: "使用样例明确指定的计算期。" }, { title: "填预期", body: "记录原始值、归一化和映射结果。" }, { title: "运行校验", body: "逐项比较而不是只看最终对错。" }, { title: "处理差异", body: "修正公式、顺序或配置后重算。" }], interpretation: "一致代表这个样例通过，不代表其他期次或其他公式自动正确。", misunderstanding: "不要为了让样例变绿而改动开奖或隐藏错误。", troubleshooting: "先核对L/D顺序、平位含义、特码和属性表。", related: ["formula-detail", "rule-terms", "formula-editor"] }),
  makeWorkflowTopic({ slug: "formula-discovery", title: "公式筛选", summary: "按训练、验证和留出样本筛选候选公式。", route: "/formula-discovery", keywords: ["筛选公式", "训练期", "验证期", "留出期"], purpose: "从候选组合中找出历史上较稳定的公式，确认后才能加入公式库。", when: "需要研究新公式且已有足够历史数据时。", orientation: "稳健、深度、高级代表搜索复杂度；训练、验证、留出必须分开读。", steps: [{ title: "选深度", body: "先用稳健模式，避免组合爆炸。" }, { title: "等待筛选", body: "计算在后台完成。" }, { title: "看三段表现", body: "不要只看训练期。" }, { title: "查错期", body: "打开逐期明细核对。" }, { title: "人工确认", body: "理解公式含义后再加入。" }], interpretation: "验证与留出表现接近训练表现，比单一高通过率更可信。", misunderstanding: "自动筛选不是自动找到未来必中的公式。", troubleshooting: "候选太少可增加数据；计算慢可降低深度。", related: ["historical-caveat", "formula-detail", "rules"] }),
  makeWorkflowTopic({ slug: "config", title: "设置", summary: "查看规则口径、属性表、高级参数、维护和使用说明。", route: "/config", keywords: ["设置", "配置", "属性表", "使用说明"], purpose: "管理影响全系统计算的属性表和规则参数，并提供完整图文说明。", when: "需要确认生肖/波色/五行映射、备份、重置或学习系统时。", orientation: "基础规则、属性表、高级设置、数据维护、使用说明五区分开；日常不要随意改高级参数。", steps: [{ title: "先查看", body: "在基础规则和属性表确认当前口径。" }, { title: "先备份", body: "修改前导出当前配置。" }, { title: "再修改", body: "只调整明确理解的字段。" }, { title: "保存校验", body: "保存后重新计算和校验。" }, { title: "学习说明", body: "在使用说明搜索页面、图表或报错。" }], interpretation: "配置变化会影响后续所有计算；旧截图或旧结果不应替代重新计算。", misunderstanding: "恢复示例数据会替换本地修改，不能当普通刷新按钮。", troubleshooting: "JSON格式错误时不要强行保存，按提示修正或恢复备份。", related: ["getting-started", "rule-terms", "troubleshooting"] }),
];
