import { makeWorkflowTopic } from "./types";

const common = { misunderstanding: "技术页面用于核对和维护，不应被当成未来结果保证。" };
export const secondaryToolTopics = [
  makeWorkflowTopic({ slug: "formula-detail", title: "公式逐期明细", summary: "逐期查看变量、表达式、输出和下一期验证。", route: "/formula-detail", keywords: ["流水账", "逐期", "错期"], purpose: "把一条公式从当前期输入到下一期验证完整展开。", when: "公式报错、连续未通过或手算不一致时。", orientation: "先选公式，再按期次从上到下阅读计算链。", steps: [{ title: "选公式", body: "选择要核对的具体公式。" }, { title: "选期次", body: "从异常或错期开始。" }, { title: "对变量", body: "核对每个平位、特码和属性。" }, { title: "对验证", body: "确认N期计算对应N+1期开奖。" }], interpretation: "每一期都应能说明输入、计算、输出和对错。", ...common, troubleshooting: "表达式异常先核对公式文本与L/D序。", related: ["sample-check", "rule-terms", "rules"], screenshotSlug: "rules" }),
  makeWorkflowTopic({ slug: "import", title: "数据导入", summary: "预览并导入CSV、TXT或Excel开奖数据。", route: "/import", keywords: ["CSV", "TXT", "Excel", "导入失败"], purpose: "把外部开奖记录安全转换为系统的6+1结构。", when: "网站同步不可用、迁移旧数据或批量补录时。", orientation: "文本/文件输入、预览结果和错误列表必须依次检查。", steps: [{ title: "准备字段", body: "按期号、平码1到平码6、特码的顺序准备。" }, { title: "选择文件", body: "或粘贴结构化文本。" }, { title: "先预览", body: "不要跳过错误行。" }, { title: "确认写入", body: "核对期数和重复项后保存。" }], interpretation: "成功条数与错误条数之和应等于输入记录数。", ...common, troubleshooting: "乱码先转UTF-8；列错位时下载模板并按标准表头填写。", related: ["draws", "draw-structure", "troubleshooting"], screenshotSlug: "draws" }),
  makeWorkflowTopic({ slug: "formula-editor", title: "公式编辑", summary: "新增或修改公式类型、顺序、表达式和目标。", route: "/formula-editor", keywords: ["新增规则", "编辑公式", "归一化"], purpose: "建立可以被统一公式引擎计算的规则记录。", when: "录入新公式或修正已确认的解析错误时。", orientation: "类型、L/D序、公式、归一化和验证目标共同决定计算。", steps: [{ title: "选类型", body: "明确是排除还是支持。" }, { title: "定顺序", body: "选择L或D并确认特码独立。" }, { title: "填表达式", body: "只使用系统支持变量。" }, { title: "保存试算", body: "用已知期次检查过程。" }, { title: "加入校验", body: "记录手算样例。" }], interpretation: "保存成功只说明格式可用，仍需样例和逐期核对。", ...common, troubleshooting: "变量不确定时不要猜，保留停用并写明来源。", related: ["sample-check", "rule-terms", "rules"], screenshotSlug: "rules" }),
  makeWorkflowTopic({ slug: "backtest", title: "高级回测", summary: "用历史期次验证公式并查看每期对错。", route: "/backtest", keywords: ["回测", "通过率", "连续"], purpose: "按统一成功口径验证公式历史表现。", when: "修改公式、比较规则或导出复盘报告时。", orientation: "通过率必须和样本数、连续未通过、错期一起看。", steps: [{ title: "确认数据", body: "使用完整且最新的历史数据。" }, { title: "运行", body: "等待所有启用规则完成。" }, { title: "看分子分母", body: "不要只看百分比。" }, { title: "查错期", body: "打开逐期过程。" }], interpretation: "排除公式实际没有落入排除集合才算通过；支持公式实际落入集合才算通过。", ...common, troubleshooting: "样本少时先补数据；计算错误先停用公式并核对。", related: ["formula-health", "formula-detail", "historical-caveat"], screenshotSlug: "rules" }),
  makeWorkflowTopic({ slug: "next-output", title: "单期输出", summary: "查看最新一期所有启用规则的直接输出。", route: "/next-output", keywords: ["下一期", "单期", "输出"], purpose: "把最新期的公式输出集中列出，便于导出和人工核对。", when: "需要一页查看全部本期输出时。", orientation: "每张卡显示公式、类型、输出和部分过程。", steps: [{ title: "确认最新期", body: "顶部期次必须正确。" }, { title: "检查异常", body: "异常卡先核对。" }, { title: "区分动作", body: "排除与支持不要混读。" }, { title: "需要时导出", body: "导出Excel保留快照。" }], interpretation: "这是当前公式计算结果集合，不是下一期开奖单。", ...common, troubleshooting: "空白时检查启用公式与数据。", related: ["one-click", "formula-result-statistics", "reports"], screenshotSlug: "one-click" }),
  makeWorkflowTopic({ slug: "reports", title: "导出报告", summary: "导出开奖、公式库、配置、回测和综合参考档案。", route: "/reports", keywords: ["导出", "备份", "Word", "Excel", "JSON"], purpose: "把当前系统数据和分析保存为可迁移、可复盘文件。", when: "换电脑、修改配置前、定期备份或分享复盘材料时。", orientation: "不同卡片导出不同数据，文件格式和内容说明写在卡片上。", steps: [{ title: "选内容", body: "先确定要备份数据、公式、配置还是报告。" }, { title: "选格式", body: "JSON适合恢复，Excel/Word适合阅读。" }, { title: "导出", body: "等待浏览器下载完成。" }, { title: "验证文件", body: "打开检查期数和更新时间。" }], interpretation: "导出文件是当时快照，不会自动随网站更新。", ...common, troubleshooting: "下载被拦截时允许本站下载；恢复前保留旧备份。", related: ["config", "draws", "candidate-pool"], screenshotSlug: "config" }),
  makeWorkflowTopic({ slug: "rule-understanding", title: "规则理解", summary: "解释公式引擎、信号、排序和核心术语。", route: "/help", keywords: ["规则说明", "Formula Engine", "Signal System", "L序", "D序"], purpose: "说明系统哪些层负责计算、哪些层只负责汇总和展示。", when: "看到专业词、计算口径不清或开发维护时。", orientation: "先理解开奖6+1、L/D顺序和排除/支持，再看技术分层。", steps: [{ title: "看开奖结构", body: "平码6个，特码1个。" }, { title: "看顺序", body: "D序只排序6个平码。" }, { title: "看动作", body: "杀类是排除，候选类是支持。" }, { title: "看验证", body: "通常N期计算，N+1期开奖验证。" }], interpretation: "公式引擎是唯一计算入口，统计和UI不能另写一套算法。", ...common, troubleshooting: "找不到术语时在使用说明搜索原词或报错文字。", related: ["draw-structure", "rule-terms", "getting-started"], screenshotSlug: "config" }),
];
